### ISSUE TITLE
Tests with Python 3.12

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna-integration#50]
### Motivation

Python 3.12 is available, but integration modules have not yet been tested with it in CI.

### Description

We should add 3.12 to the python-version matrix in the CI configuration.

https://github.com/optuna/optuna-integration/blob/e8e371803e1a9f0983679cccdc80d23325dc1e2d/.github/workflows/tests.yml#L32

Additionally, if the CI fails with Python 3.12, we may need to update the codebase to resolve compatibility issues.

If the tests pass as expected, we can also update the supported Python versions in README.md and pyproject.toml.
https://github.com/optuna/optuna-integration/blob/e8e371803e1a9f0983679cccdc80d23325dc1e2d/README.md?plain=1#L3
https://github.com/optuna/optuna-integration/blob/e8e371803e1a9f0983679cccdc80d23325dc1e2d/pyproject.toml#L19-L20

**Comment by DanielAvdar** [comment]
It seems like the main issue with Python 3.12 is the dependency problem related to TensorFlow. Specifically, there's a message stating: "No matching distribution found for tensorflow; extra == 'all'". You can find more details [here](https://github.com/DanielAvdar/optuna-integration/actions/runs/7884876555/job/21514808675).

**Comment by DanielAvdar** [comment]
tensorflow/tensorflow#62003 
TensorFlow does not currently support Python 3.12.

**Comment by toshihikoyanase** [comment]
Thank for your investigation. We may need to skip such tests in Python 3.12.
